#!/bin/bash

#SBATCH --job-name vecadd-opencl
#SBATCH -N1
#SBATCH --gres=gpu:1
#SBATCH --time 00:15:00
#SBATCH --partition gpu
#SBATCH --output vecadd-opencl.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
OCL_DEVICE=1 ./vecadd-opencl
